=== ZheWang711/XQuery/test_review.dtd
<!ELEMENT reviews (entry*)>
        <!ELEMENT entry   (year, title, price, review)>
        <!ELEMENT year   (#PCDATA)>
        <!ELEMENT title   (#PCDATA)>
        <!ELEMENT price   (#PCDATA)>
        <!ELEMENT review  (#PCDATA)>

=== ZheWang711/XQuery/test_review.xml
<?xml version="1.0"?>
<!DOCTYPE reviews SYSTEM "test_review.dtd">

<reviews>
    <entry>
        <year>2000</year>
        <title>Data on the Web</title>
        <price>34.95</price>
        <review>
            A very good discussion of semi-structured database
            systems and XML.
        </review>
    </entry>
    <entry>
        <year>1992</year>
        <title>Advanced Programming in the Unix environment</title>
        <price>65.95</price>
        <review>
            A clear and detailed discussion of UNIX programming.
        </review>
    </entry>
    <entry>
        <year>1994</year>
        <title>TCP/IP Illustrated</title>
        <price>78.23</price>
        <review>
            One of the best books on TCP/IP.
        </review>
    </entry>
</reviews>
